language: node_js

node_js:
  - "0.10"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - gem install sass
  - gem install compass

before_script:
  - npm install --quiet -g grunt-cli karma bower
  - npm install
  - bower install

script: grunt

